### ISSUE TITLE
Thoughts about potentially leveraging ERC-5732 Commit Interface?

### ISSUE THREAD

**Issue by xinbenlv** [a16z/auction-zoo#8]
Hi, thanks for @sbacha's sharing, I came across this repository.

For this line 
https://github.com/a16z/auction-zoo/blob/dd479272276a2b67aec6fff57ac6a264b7b5bb9c/src/sealed-bid/over-collateralized-auction/OverCollateralizedAuction.sol#L190

```solidity
    function commitBid(
        address tokenContract, 
        uint256 tokenId, 
        bytes20 commitment
    ) ... { ... }
```

I like to get some feedback about thoughts on considering also supporting [ERC5732 Commit Interface](https://eips.ethereum.org/EIPS/eip-5732)

```solidity
    function commitFrom(
        address _from,
        bytes32 _commitment,
        bytes calldata _extraData)
    payable external returns(uint256 timePoint) {
             ...
    }
```

For example, it can be done by adding 

```solidity
    function commitFrom(
        address _from,
        bytes32 _commitment,
        bytes calldata _extraData)
    payable external returns(uint256 timePoint) {
             address tokenContract = _extraData[0:20];
             uint256 tokenId = _extraData[20:52];
             _commitBid(address tokenContract, uint256 tokenId, bytes20 commitment);
    }
``` 

The benefit is in the future if we want to expand this OverCollateralizedAuction to other type of assets, e.g. 
ERC1155, we could also add `amount`

```
    function commitFrom(
        address _from,
        bytes32 _commitment,
        bytes calldata _extraData)
    payable external returns(uint256 timePoint) {
             address tokenContract = _extraData[0:20];
             address tokenId = _extraData[20:52];
             uint256 amount = _extraData[52:84];  // Newline to support ERC1155
             /*a newer version of*/ ... _commitBidERC1155(address tokenContract, uint256 tokenId, bytes20 commitment);
    }
```

And thus mobile or web clients who have been built to  `commitFrom` would be able to support this change with backward compatibility.

Thanks!

**Comment by moodlezoup** [comment]
Thanks for the suggestion –– the contracts in this repository are intended for education, so in the interest of keeping the interface as simple and intuitive as possible I'm going to refrain from implementing the ERC5732 interface in this repository. That said, anyone is welcome to fork this repo and add support!
